### ISSUE TITLE
Are there better alternatives than uuidtools nowdays?

### ISSUE THREAD

**Issue by mariozaizar** [sporkmonger/uuidtools#43]
I'm had been using uuidtools gem for years, thanks for it! 👍 

Because the last commit is from Aug 11, 2015, I'm thinking of using another UUID generator, 
Are there better alternatives nowadays? In your opinion whats the best UUID generator in ruby (as 2017)?

**Comment by sriedel** [comment]
It depends on what your requirements are.

With modern rubies you can use SecureRandom.uuid for V4 UUIDs (SecureRandom is in the standard library). Rails offerns functions for V3, V4 and V5 UUIDs out of the box.
